import {test} from 'node:test';
import assert from 'node:assert/strict';
import {channelNotices,pipelineChannel} from '../lib/channel-notifications';
import {validateWorkerResult} from '../lib/worker';
const job={id:'job1',number:12,title:'Test <@everyone>',status:'INTERNAL_REVIEW',type:'Static',dueAt:new Date('2026-10-10T12:00:00Z'),client:{name:'Client'},assignee:{name:'Preston',slackUserId:'U08HZ70RPK4'}};
test('assignment and all forward statuses reach the shared pipeline channel with brief code',()=>{for(const to of ['BRIEFED','IN_PRODUCTION','INTERNAL_REVIEW','CLIENT_REVIEW','APPROVED','DELIVERED']){const n=channelNotices(job,{to},'https://example.com');assert.equal(n.length,1);assert.equal(n[0].channelId,pipelineChannel.id);assert.match(n[0].text,/GG-BR-00012/);assert.match(n[0].text,/\?job=job1/);assert.match(n[0].text,/&lt;@everyone&gt;/);}});
test('both QA return paths notify the shared pipeline once with feedback and revision deadline',()=>{for(const from of ['INTERNAL_REVIEW','CLIENT_REVIEW']){const n=channelNotices(job,{from,to:'IN_PRODUCTION',reason:'Fix copy',feedbackUrl:'https://frame.io/review',revisionDue:'2026-10-14'},'https://example.com/');assert.equal(n.length,1);assert.equal(n[0].channelId,pipelineChannel.id);assert.match(n[0].text,/Revision due: 2026-10-14/);assert.match(n[0].text,/Fix copy/);assert.match(n[0].text,/https:\/\/frame.io\/review/);}});
test('all designers and unassigned briefs use the shared pipeline channel',()=>{for(const assignee of [null,{name:'New designer',slackUserId:'UOTHER'}]){const n=channelNotices({...job,assignee},{to:'BRIEFED'},'https://example.com');assert.equal(n.length,1);assert.equal(n[0].channelId,pipelineChannel.id);}});
test('channel receipt must match exact destination; buyer delivery still requires a DM',()=>{const action={id:'test',kind:'slack' as const,channelId:pipelineChannel.id};validateWorkerResult(action,{channel:pipelineChannel.id,ts:'123.456'});assert.throws(()=>validateWorkerResult(action,{channel:'CWRONG',ts:'123.456'}));assert.throws(()=>validateWorkerResult({id:'buyer',kind:'slack'},{channel:pipelineChannel.id,ts:'123.456'}));});
