'use client';
import {NewBrief} from './new-brief';
import {briefCode} from '@/lib/brief-plan';
import {signOut} from 'next-auth/react';
import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, Bell, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, ExternalLink, Filter, FolderKanban, LayoutDashboard, Link2, Menu, MoreHorizontal, Plus, Search, Settings2, Sparkles, Users, X } from 'lucide-react';
import { CreativeType, Job, seedJobs, statuses, Status, transition, transitions, variantsFor } from '@/lib/workflow';
import {deliveryFilename,routeQa,type QaPerson} from '@/lib/assurance';
import {WorkspaceReadiness,ClientConnections,DeliveryProgress} from './readiness-ui';
import {AssuranceSettings,AssetEvidence,TrackedManifest,previewClient,previewAssets,previewReleaseGate,BriefRuleReference} from './assurance-ui';
import { sharedFields, typeFields, type BriefField } from '@/lib/templates';

import {launchSummary} from '@/lib/launch-summary';
import {stageTitle} from '@/lib/pipeline';
import {ReviewQueues} from './review-queues';
import {PipelineBoard,JobHistory} from './pipeline-board';
import {JobMovement} from './job-movement';
import {ActivityLog,IntakeQueue,Launches,Planning,Readiness} from './operations-ui';
import {localDate,operationsFor,type PlanClient,type IntakeDraft,type JobOperations} from '@/lib/operations';

const key='ghost-growth-jobs-v1';
const serverMode=process.env.NEXT_PUBLIC_DATA_MODE==='server';
async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const json=await response.json();if(!response.ok)throw new Error(json.error||'Request failed');return json as T;}
const palette: Record<Status,string>={ 'Briefed':'purple','In Production':'blue','Internal Review':'amber','Client Review':'rose','Approved':'green','Delivered':'slate' };
function dateLabel(value:string) { return new Date(value+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}); }
function initials(name:string) { return name.split(' ').map(s=>s[0]).join('').slice(0,2).toUpperCase(); }
function roleLabel(type:CreativeType) { return type==='Video'||type==='Motion'||type==='UGC'?'Editor':'Designer'; }
export default function Dashboard() {
  const [today,setToday]=useState(localDate());
  useEffect(()=>{setToday(localDate());const timer=setInterval(()=>setToday(localDate()),60000);return ()=>clearInterval(timer)},[]);
  const [jobs,setJobs]=useState<Job[]>(serverMode?[]:seedJobs); const [ready,setReady]=useState(false);
  const [query,setQuery]=useState(''); const [client,setClient]=useState('All clients'); const [view,setView]=useState('Pipeline');
  const [selected,setSelected]=useState<Job|null>(null); const [creating,setCreating]=useState(false); const [toast,setToast]=useState('');
  const [motionDraft,setMotionDraft]=useState<IntakeDraft|null>(null);
  const [clientPlans,setClientPlans]=useState<PlanClient[]>([]);
  const [configuredClients,setConfiguredClients]=useState<string[]>([]);const [makers,setMakers]=useState<string[]>(serverMode?[]:['Alex Morgan','Sam Rivera','Taylor Chen']);const [role,setRole]=useState(serverMode?'LOADING':'ADMIN');
  const [templateConfig,setTemplateConfig]=useState<Record<string,BriefField[]>>({});const [ruleConfig,setRuleConfig]=useState<Record<string,string[]>>({});
  useEffect(()=>{ if(serverMode){api<{jobs:Job[]}>('/api/jobs').then(data=>setJobs(data.jobs)).catch(e=>setToast(e.message)).finally(()=>setReady(true));return;} try { const saved=localStorage.getItem(key); if(saved) setJobs(JSON.parse(saved)); } catch {} setReady(true); },[]);
  useEffect(()=>{ if(ready&&!serverMode) localStorage.setItem(key,JSON.stringify(jobs)); },[jobs,ready]);
  useEffect(()=>{if(!toast)return; const id=setTimeout(()=>setToast(''),3500); return ()=>clearTimeout(id)},[toast]);
  useEffect(()=>{if(!serverMode)return;api<{user:{role:string}}>('/api/me').then(d=>setRole(d.user.role)).catch(()=>{});api<{clients:{name:string}[]}>('/api/admin/clients').then(d=>setConfiguredClients(d.clients.map(c=>c.name))).catch(()=>{});api<{users:{name:string;role:string}[]}>('/api/admin/users').then(d=>setMakers(d.users.filter(u=>u.role==='MAKER').map(u=>u.name))).catch(()=>{});},[]);
  useEffect(()=>{if(!serverMode)return;api<{templates:{type:string;fields:BriefField[]}[];rules:{type:string;rule:{letters:string[]}}[]}>('/api/admin/templates').then(d=>{setTemplateConfig(Object.fromEntries(d.templates.map(t=>[t.type,t.fields])));setRuleConfig(Object.fromEntries(d.rules.map(r=>[r.type,r.rule.letters])))}).catch(()=>{})},[]);
  useEffect(()=>{if(!serverMode)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')api<{jobs:Job[]}>('/api/jobs').then(d=>{setJobs(d.jobs);setSelected(current=>current&&['Approved','Delivered'].includes(current.status)?d.jobs.find(j=>j.id===current.id)||current:current)}).catch(()=>{})},30000);return ()=>clearInterval(timer)},[]);
  useEffect(()=>{if(serverMode){api<{clients:PlanClient[]}>('/api/operations/plans').then(d=>setClientPlans(d.clients)).catch(()=>{})}else{try{const plans=JSON.parse(localStorage.getItem('gg-plans')||'[]') as PlanClient[];setClientPlans(plans);setJobs(current=>current.map(job=>{const p=plans.find(c=>c.name===job.client)?.plan;return {...job,clientPriority:p?.priority||'Normal',deliverySchedule:p?.deliverySchedule}}))}catch{}}},[]);
  const clients=useMemo(()=>['All clients',...Array.from(new Set(jobs.map(j=>j.client)))], [jobs]);
  const visible=jobs.filter(j=>(client==='All clients'||j.client===client) && `${j.number} ${j.title} ${j.client} ${j.campaign} ${j.assignee}`.toLowerCase().includes(query.toLowerCase()));
  const counts=Object.fromEntries(statuses.map(s=>[s,visible.filter(j=>j.status===s).length])) as Record<Status,number>;
  const open=jobs.filter(j=>j.status!=='Delivered').length; const review=jobs.filter(j=>j.status==='Internal Review'||j.status==='Client Review').length; const due=jobs.filter(j=>j.status!=='Delivered'&&j.due<=today).length;
  async function saveJob(next:Job) {try {const old=selected?.id===next.id?selected:jobs.find(j=>j.id===next.id)!;const changes={expectedUpdatedAt:old.updatedAt,...(JSON.stringify(old.brief)!==JSON.stringify(next.brief)?{brief:next.brief}:{}),...(old.assignee!==next.assignee?{assignee:next.assignee==='Unassigned'?'':next.assignee}:{}),...(old.due!==next.due?{due:next.due}:{}),...(old.reviewUrl!==next.reviewUrl?{reviewUrl:next.reviewUrl}:{})};const updated=serverMode?(await api<{job:Job}>(`/api/jobs/${next.id}`,{method:'PATCH',body:JSON.stringify(changes)})).job:{...next,operations:JSON.stringify(old.brief)!==JSON.stringify(next.brief)?{...operationsFor(next),checklist:[],approvalEvidenceUrl:''}:next.operations,briefRevision:JSON.stringify(old.brief)!==JSON.stringify(next.brief)?(old.briefRevision||1)+1:old.briefRevision};if(!serverMode&&JSON.stringify(old.brief)!==JSON.stringify(next.brief)){localStorage.setItem(`gg-assets-${next.id}`,JSON.stringify(previewAssets(next).map(a=>({...a,review:null}))));}setJobs(prev=>prev.map(j=>j.id===updated.id?updated:j));setSelected(updated);setToast('Job details saved');return true}catch(e){setToast((e as Error).message);return false}}
  async function saveOperations(job:Job,operations:JobOperations){const updated=serverMode?(await api<{job:Job}>(`/api/jobs/${job.id}/operations`,{method:'PATCH',body:JSON.stringify(operations)})).job:{...job,operations,updatedAt:new Date().toISOString()};setJobs(prev=>prev.map(j=>j.id===updated.id?updated:j));setSelected(updated);}
  async function advance(job:Job,next:Status):Promise<string|null> {try {if(!serverMode&&['Approved','Client Review'].includes(next)){const gate=previewReleaseGate(job);if(gate)throw new Error(gate);}if(!serverMode&&next==='Internal Review'){const c=previewClient(job);const team=JSON.parse(localStorage.getItem('gg-qa-team')||'[]') as QaPerson[];const route=routeQa(c.governance,team);if(!route.person)throw new Error(route.reason);}if(!serverMode&&next==='In Production'&&job.status!=='Briefed'){const assets=previewAssets(job).map(a=>({...a,review:null}));localStorage.setItem(`gg-assets-${job.id}`,JSON.stringify(assets));}const updated=serverMode?(await api<{job:Job}>(`/api/jobs/${job.id}/transitions`,{method:'POST',body:JSON.stringify({next,reason:next==='In Production'&&job.status!=='Briefed'?operationsFor(job).revisionReason:undefined,approvalEvidenceUrl:next==='Approved'?operationsFor(job).approvalEvidenceUrl:undefined})})).job:transition(job,next,'You');setJobs(prev=>prev.map(j=>j.id===updated.id?updated:j));setSelected(updated);setToast(`#${job.number} moved to ${next}`);return null} catch(e) {return (e as Error).message}}
  async function create(job:Job){try{const created=serverMode?(await api<{job:Job}>('/api/jobs',{method:'POST',body:JSON.stringify(job)})).job:job;setJobs(prev=>[created,...prev]);setCreating(false);setMotionDraft(null);setSelected(created);setToast(`${briefCode(created.number)} created · ${created.variants.length} ${created.type.toLowerCase()} assets`)}catch(e){setToast((e as Error).message);throw e}}
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">G<span>G</span></div><div><strong>Ghost Growth</strong><small>CREATIVE OPERATIONS</small></div></div>
      <div className="workspace"><span className="workspace-avatar">GG</span><span><strong>Ghost Growth</strong><small>Workspace</small></span><ChevronDown size={15}/></div>
      <div className="nav-group"><div className="nav-caption">WORKSPACE</div>{[['Pipeline',LayoutDashboard],['Campaigns',FolderKanban],['Quality & rules',Check],['Planning',CalendarDays],['Intake',Link2],['Attention',Bell],['Launches',ArrowRight],['Review queue',Users],['Delivery',Check],['Activity',Activity]].filter(([label])=>!serverMode||!['Planning','Intake','Quality & rules'].includes(label as string)||['ADMIN','STRATEGIST'].includes(role)).map(([label,Icon])=><button key={label as string} className={`nav-item ${view===label?'active':''}`} onClick={()=>setView(label as string)}><Icon size={18}/><span>{label as string}</span>{label==='Review queue'&&review>0?<b>{review}</b>:null}</button>)}</div>
      <div className="nav-group bottom-nav"><div className="nav-caption">SETTINGS</div><button className="nav-item" onClick={()=>setView('Settings')}><Settings2 size={18}/>Settings</button><button className="nav-item" onClick={()=>setView('Settings')}><CircleHelp size={18}/>Help & guidance</button></div>
      <div className="sidebar-user"><span className="user-avatar">GG</span><span><strong>Creative Team</strong><small>{serverMode?'Connected workspace':'Workspace preview'}</small></span><MoreHorizontal size={18}/></div>
    </aside>
    <main className="main"><header className="topbar"><div className="crumb"><Menu size={18}/><span>Workspace</span><span className="slash">/</span><strong>{view}</strong></div><div className="top-actions"><span className="today"><CalendarDays size={16}/> {new Date(today+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'America/Toronto',weekday:'long',month:'long',day:'numeric'})}</span><button className="icon-btn" aria-label="Notifications" onClick={()=>setToast(`${review} jobs are awaiting review`)}><Bell size={18}/><i/></button><span className="top-avatar">GG</span></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">CREATIVE WORKSPACE <span>•</span> OVERVIEW</div><h1>{view==='Pipeline'?'Creative pipeline':view}</h1><p>{view==='Pipeline'?'Track every creative job from the first brief to final delivery.':view==='Campaigns'?'Browse campaigns and their creative jobs.':view==='Review queue'?'Gate 1: internal QA. Gate 2: client QA. Final approval starts delivery.':view==='Delivery'?'Approved assets awaiting final handoff and completed deliveries.':'Creative operations workspace.'}</p></div>{serverMode&&<button className="secondary-btn" onClick={async()=>{try{const d=await api<{jobs:Job[]}>('/api/jobs');setJobs(d.jobs);if(selected)setSelected(d.jobs.find(j=>j.id===selected.id)||null);setToast('Pipeline refreshed')}catch(e){setToast((e as Error).message)}}}>Refresh pipeline</button>}{(!serverMode||role==='ADMIN'||role==='STRATEGIST')&&<button className="primary-btn" onClick={()=>{setMotionDraft(null);setCreating(true)}}><Plus size={18}/> New brief</button>}</div>
      {view==='Settings'?<>{serverMode&&role==='ADMIN'&&<section className="ops-card"><a className="secondary-btn" href="/connections/qa">Client & format QA routes</a><h2>Motion / Runneth</h2><p>Connect your Motion workspace and verify available reports and documents.</p><a className="secondary-btn" href="/connections/motion">Manage Motion connection</a></section>}{(!serverMode||['ADMIN','STRATEGIST'].includes(role))?<WorkspaceReadiness/>:<p className="ops-card">Your administrator manages workspace connections and client rules.</p>}{serverMode&&<button className="secondary-btn" onClick={()=>void signOut({redirectTo:'/sign-in'})}>Sign out</button>}{serverMode&&role==='ADMIN'&&<><ClientConnections/><AdminSettings onChanged={()=>{api<{clients:{name:string}[]}>('/api/admin/clients').then(d=>setConfiguredClients(d.clients.map(c=>c.name)));api<{users:{name:string;role:string}[]}>('/api/admin/users').then(d=>setMakers(d.users.filter(u=>u.role==='MAKER').map(u=>u.name)));}}/></>}</>:view==='Review queue'?<ReviewQueues jobs={jobs} onOpen={setSelected}/>:view==='Quality & rules'?<AssuranceSettings jobs={jobs}/>:view==='Activity'?<ActivityLog/>:view==='Planning'?<Planning jobs={jobs} onPlansChanged={plans=>{setClientPlans(plans);setJobs(current=>current.map(job=>{const p=plans.find(c=>c.name===job.client)?.plan;return {...job,clientPriority:p?.priority||'Normal',deliverySchedule:p?.deliverySchedule}}))}}/>:view==='Intake'?<IntakeQueue onPick={draft=>{setMotionDraft(draft);setCreating(true)}}/>:view==='Launches'?<Launches onRecordsChanged={records=>setJobs(current=>current.map(job=>({...job,...launchSummary(job.variants,records.filter(r=>r.jobId===job.id))}))) } jobs={jobs} editable={!serverMode||['ADMIN','STRATEGIST','MEDIA_BUYER'].includes(role)} onIterate={draft=>{if(serverMode&&!['ADMIN','STRATEGIST'].includes(role)){setToast('Ask a strategist to create the iteration brief.');return;}setMotionDraft(draft);setCreating(true)}}/>:view==='Pipeline'?<PipelineBoard plans={clientPlans} onPlan={()=>setView('Planning')} jobs={jobs} clients={configuredClients} today={today} ready={ready} canCreate={!serverMode||['ADMIN','STRATEGIST'].includes(role)} onOpen={job=>setSelected(job)} onCreate={()=>{setMotionDraft(null);setCreating(true)}}/>:<>
      <div className="stats"><div className="stat"><div className="stat-icon purple"><FolderKanban size={20}/></div><div><span>Active jobs</span><strong>{open}</strong><small>Across all stages</small></div></div><div className="stat"><div className="stat-icon amber"><Clock3 size={20}/></div><div><span>In review</span><strong>{review}</strong><small>Awaiting feedback</small></div></div><div className="stat"><div className="stat-icon rose"><CalendarDays size={20}/></div><div><span>Due today or earlier</span><strong>{due}</strong><small>Needs attention</small></div></div><div className="stat"><div className="stat-icon green"><Check size={20}/></div><div><span>Delivered</span><strong>{jobs.filter(j=>j.status==='Delivered').length}</strong><small>Ready for media buying</small></div></div></div>
      <div className="board-panel"><div className="board-head"><div><h2>{view==='Pipeline'?'Pipeline board':view}</h2><span>{visible.length} jobs</span></div><div className="board-controls"><label className="search"><Search size={16}/><input placeholder="Search jobs..." value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select"><Filter size={16}/><select value={client} onChange={e=>setClient(e.target.value)}>{clients.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label></div></div>
      <div className="list-view">{visible.filter(j=>view==='Attention'?j.status!=='Delivered'&&(Boolean(operationsFor(j).blockerReason)||j.due<=today||j.status==='In Production'&&Boolean(operationsFor(j).revisionDue)&&operationsFor(j).revisionDue<=today):view==='Review queue'?['Internal Review','Client Review'].includes(j.status):view==='Delivery'?['Approved','Delivered'].includes(j.status):true).map(j=><button key={j.id} onClick={()=>setSelected(j)}><span className="list-num">#{j.number}</span><span><strong>{j.title}</strong><small>{j.client} · {j.campaign}</small></span><span className={`list-status ${palette[j.status]}`}>{stageTitle(j.status)}</span><ArrowRight size={17}/></button>)}</div>
      </div></>}<div className="footer-note"><Sparkles size={15}/>{serverMode?'Connected workspace · Changes are saved on the server':'Preview workspace · Changes are saved in this browser'}</div></div>
    </main>
    {selected&&<JobDrawer onLaunch={()=>{setSelected(null);setView('Launches')}} onRefresh={async()=>{if(serverMode&&selected){const d=await api<{job:Job}>(`/api/jobs/${selected.id}`);setSelected(d.job);setJobs(prev=>prev.map(j=>j.id===d.job.id?d.job:j))}}} role={role} makers={makers} onIterate={draft=>{if(serverMode&&!['ADMIN','STRATEGIST'].includes(role)){setToast('Ask a strategist to create the iteration brief.');return;}setSelected(null);setMotionDraft(draft);setCreating(true)}} key={selected.id} job={selected} onOperations={ops=>saveOperations(selected,ops)} onClose={()=>setSelected(null)} onAdvance={advance} onSave={saveJob}/>}
    {creating&&<NewBrief onClose={()=>{setCreating(false);setMotionDraft(null)}} onCreate={create} nextNumber={Math.max(500,...jobs.map(j=>j.number))+1} clients={serverMode?configuredClients:['CareBox','Northstar','Ghost Growth']} makers={makers} motionDraft={motionDraft} templateConfig={templateConfig} ruleConfig={ruleConfig}/>}
    {toast&&<div className="toast">{toast}</div>}
  </div>;
}
function JobDrawer({onLaunch,onRefresh,role,makers,job,onClose,onAdvance,onSave,onOperations,onIterate}:{onLaunch:()=>void;onRefresh:()=>Promise<void>;role:string;makers:string[];job:Job;onIterate:(draft:IntakeDraft)=>void;onOperations:(ops:JobOperations)=>Promise<void>;onClose:()=>void;onAdvance:(j:Job,s:Status)=>Promise<string|null>;onSave:(j:Job)=>Promise<boolean>}){
  const [tab,setTab]=useState('Overview'); const [review,setReview]=useState(job.reviewUrl); const [assignee,setAssignee]=useState(job.assignee); const [due,setDue]=useState(job.due);const [editingBrief,setEditingBrief]=useState(false);const [briefDraft,setBriefDraft]=useState(job.brief||{});
  const strategic=!serverMode||['ADMIN','STRATEGIST'].includes(role);
  const editable=!['Approved','Delivered'].includes(job.status);
  const allowed=transitions[job.status].filter(()=>strategic||(role==='MAKER'&&['Briefed','In Production'].includes(job.status))||(role==='QA'&&job.status==='Internal Review'));
  const canReview=editable&&(strategic||role==='MAKER')&&['Briefed','In Production'].includes(job.status);
  const exampleName=deliveryFilename({scope:job.clientCode||'GG',type:job.type.toUpperCase(),descriptor:`job${job.number}-a`,aspect:'9x16',version:1,extension:job.type==='Static'?'png':'mp4'});
  return <div className="modal-backdrop" onMouseDown={onClose}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-top"><span>JOB DETAILS <span className="divider">/</span> #{job.number}</span><button className="icon-btn" aria-label="Close job details" onClick={onClose}><X size={20}/></button></div><div className="drawer-body"><div className="drawer-title"><span className={`status-badge ${palette[job.status]}`}>{stageTitle(job.status)}</span><h2>{job.title}</h2><p>{job.client} · {job.campaign}{job.parentJobId?' · Iteration':''}</p></div><JobMovement onLaunch={onLaunch} job={job} allowed={allowed} onAdvance={onAdvance} onNavigate={setTab}/><div className="tabs">{['Overview','Variants','Review','QA & blockers','Assets & results','Delivery','History'].map(t=><button className={tab===t?'current':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Overview'&&<div className="drawer-section"><h3>Production details</h3><div className="inline-hint"><strong>{briefCode(job.number)}</strong> · {job.variants.length} {job.type.toLowerCase()} assets · {job.source} source</div><div className="field-grid"><label>Campaign<input value={job.campaign} readOnly/></label><label>Creative type<input value={job.type} readOnly/></label><label>{roleLabel(job.type)}<select disabled={!strategic||!editable} value={assignee} onChange={e=>setAssignee(e.target.value)}>{Array.from(new Set(['Unassigned',assignee,...makers])).map(m=><option key={m}>{m}</option>)}</select></label><label>Due date<input disabled={!strategic||!editable} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><label className="full-field">Concept<input value={job.concept} readOnly/></label><button disabled={!strategic||!editable} className="secondary-btn" onClick={()=>onSave({...job,assignee,due})}>Save details</button>{job.brief&&Object.keys(job.brief).length>0&&<><div className="section-divider"/><h3>Creative brief · revision {job.briefRevision||1}</h3>{strategic&&['Briefed','In Production'].includes(job.status)&&<button className="secondary-btn" onClick={()=>{setBriefDraft(job.brief||{});setEditingBrief(!editingBrief)}}>{editingBrief?'Cancel edit':'Edit brief'}</button>}{editingBrief&&<div className="ops-form">{Object.keys(briefDraft).filter(k=>!['assetCount','intakeEventId','motionEventId','qaReviewerId','qaReviewerName','qaRouteVersion'].includes(k)).map(k=><label key={k}>{k}<textarea value={briefDraft[k]} onChange={e=>setBriefDraft(p=>({...p,[k]:e.target.value}))}/></label>)}<p>Saving creates a brief revision and clears asset QA. Register revised assets before review.</p><button className="primary-btn" onClick={async()=>{if(await onSave({...job,brief:briefDraft}))setEditingBrief(false)}}>Save brief revision</button></div>}<div className="brief-readout">{Object.entries(job.brief).filter(([,value])=>value).map(([key,value])=><div key={key}><small>{key.replace(/([A-Z])/g,' $1')}</small><span>{value}</span></div>)}</div></>}</div>}
    {tab==='History'&&<JobHistory job={job} server={serverMode}/>}
    {tab==='QA & blockers'&&<Readiness job={job} onSave={onOperations}/>}
    {tab==='Assets & results'&&<AssetEvidence job={job} onJobChanged={onRefresh} onIterate={onIterate}/>}
    {tab==='Variants'&&<div className="drawer-section"><h3>Planned assets · {job.variants.length} {job.type.toLowerCase()} outputs</h3><p className="muted">Brief {briefCode(job.number)}. Each letter identifies one deliverable. Revisions keep the same letter and increase the version.</p><div className="variant-list">{job.variants.map(v=><div key={v}><span className="variant-letter">{v}</span><span>{briefCode(job.number)}-{v}</span><small>{job.type} · Initial version v01</small></div>)}</div><div className="naming-preview"><strong>Current delivery naming</strong><code>{exampleName}</code><small>Example only. Register exact scope, descriptor, aspect and revision under Assets & results.</small></div></div>}
    {tab==='Review'&&<div className="drawer-section"><h3>Review surface</h3><p className="muted">Add the Figma or Frame.io link where your team and client leave comments.</p><label className="full-field">Review link<input disabled={!canReview} type="url" placeholder="https://figma.com/ or https://frame.io/" value={review} onChange={e=>setReview(e.target.value)}/></label><button disabled={!canReview} className="secondary-btn" onClick={()=>onSave({...job,reviewUrl:review})}>Save review link</button>{job.reviewUrl&&<a className="external-link" href={job.reviewUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Open review surface</a>}<div className="review-callout"><Users size={18}/><span>Internal QA: <strong>{job.qa}</strong><br/>Client approval is recorded manually after feedback is resolved.<br/>Approval owner: {job.approvalOwner||'Strategist'}<br/>Release owner: {job.releaseOwner||job.mediaBuyer}</span></div></div>}
    {tab==='Delivery'&&<div className="drawer-section"><h3>Final delivery</h3><p className="muted">Every delivery uses tracked asset revisions and generated filenames. Google Drive holds the final files in version folders.</p><div className="delivery-steps"><div><span className="step-index">1</span><span>Approved assets retrieved</span><b>{job.status==='Delivered'?'Complete':job.status==='Approved'?'Pending':'Locked'}</b></div><div><span className="step-index">2</span><span>Names and Drive upload verified</span><b>{job.driveUrl?'Complete':'Pending'}</b></div><div><span className="step-index">3</span><span>Media buyer Slack DM confirmed</span><b>{job.deliveryReceipt||'Pending'}</b></div></div>{(!serverMode||!job.deliveryBatchId)&&<div className="naming-preview"><strong>Filename example · SCOPE_TYPE_descriptor_aspect_vNN</strong><code>{exampleName}</code><small>Each variant has a distinct descriptor. Existing completed delivery records keep their original names.</small></div>}{job.driveUrl&&<a className="external-link" href={job.driveUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> View in Google Drive</a>}{serverMode&&job.deliveryBatchId&&<DeliveryProgress batchId={job.deliveryBatchId}/>}{job.status==='Approved'&&serverMode&&strategic&&job.deliveryBatchId&&<TrackedManifest job={job}/>}</div>}
  </div></aside></div>;
}

function AdminSettings({onChanged}:{onChanged:()=>void}){
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState('MAKER');const [slack,setSlack]=useState('');
 const [client,setClient]=useState('');const [code,setCode]=useState('');const [drive,setDrive]=useState('');const [buyer,setBuyer]=useState('');const [qa,setQa]=useState('');const [message,setMessage]=useState('');
 async function addUser(e:React.FormEvent){e.preventDefault();try{await api('/api/admin/users',{method:'POST',body:JSON.stringify({name,email,role,slackUserId:slack})});setMessage('User saved');setName('');setEmail('');setSlack('');onChanged()}catch(err){setMessage((err as Error).message)}}
 async function addClient(e:React.FormEvent){e.preventDefault();try{await api('/api/admin/clients',{method:'POST',body:JSON.stringify({name:client,code,driveRootId:drive,mediaBuyerEmail:buyer||undefined,qaEmails:qa.split(',').map(s=>s.trim()).filter(Boolean)})});setMessage('Client saved');setClient('');setCode('');setDrive('');setBuyer('');setQa('');onChanged()}catch(err){setMessage((err as Error).message)}}
 return <div className="settings-grid"><form className="settings-card" onSubmit={addUser}><h2>Add a team member</h2><p>Only listed people can sign in. Assign their role and Slack user ID.</p><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{['ADMIN','STRATEGIST','MAKER','QA','MEDIA_BUYER'].map(r=><option key={r}>{r}</option>)}</select></label><label>Slack user ID<input value={slack} onChange={e=>setSlack(e.target.value)}/></label><button className="primary-btn">Save user</button></form><form className="settings-card" onSubmit={addClient}><h2>Add a client</h2><p>Client code is used in delivery filenames. Add users first, then assign QA and media buyer emails.</p><label>Client name<input required value={client} onChange={e=>setClient(e.target.value)}/></label><label>Client code<input required placeholder="e.g. CBX" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Google Drive root folder ID<input value={drive} onChange={e=>setDrive(e.target.value)}/></label><label>Media buyer email<input type="email" value={buyer} onChange={e=>setBuyer(e.target.value)}/></label><label>QA emails, comma separated<input value={qa} onChange={e=>setQa(e.target.value)}/></label><button className="primary-btn">Save client</button></form>{message&&<div className="settings-message">{message}</div>}</div>
}
function MotionInbox({onPick}:{onPick:(draft:{title:string;eventId:string})=>void}){
 const [events,setEvents]=useState<{id:string;receivedAt:string;payload:{task?:{title?:string;id?:string};type?:string}}[]>([]);const [message,setMessage]=useState('');
 useEffect(()=>{api<{events:typeof events}>('/api/inbox/motion').then(d=>setEvents(d.events)).catch(e=>setMessage(e.message))},[]);
 return <div className="board-panel"><div className="board-head"><div><h2>Motion import candidates</h2><span>{events.length} tasks awaiting a strategist</span></div></div><div className="list-view">{events.map(event=><button key={event.id} onClick={()=>onPick({title:event.payload.task?.title||'Motion task',eventId:event.id})}><span className="list-num">Motion</span><span><strong>{event.payload.task?.title||'Untitled task'}</strong><small>{event.payload.task?.id||event.id} · {new Date(event.receivedAt).toLocaleString()}</small></span><span className="list-status purple">Create brief</span><ArrowRight size={17}/></button>)}{events.length===0&&<p className="muted" style={{padding:20}}>{message||'No Motion tasks are waiting to be imported.'}</p>}</div></div>
}
