import {NextResponse} from 'next/server';
import {db} from '@/lib/db';
import {currentUser,mayCreate,mayView} from '@/lib/permissions';
import {error,jsonBody} from '@/lib/api';
import {metricSchema} from '@/lib/assurance';
export async function GET(request:Request){const user=await currentUser();if(!user)return error('Sign in required',401);const jobId=new URL(request.url).searchParams.get('jobId');if(!jobId)return error('Job ID required');const job=await db.job.findUnique({where:{id:jobId}});if(!job)return error('Job not found',404);if(!await mayView(user,job))return error('Not permitted',403);const rows=await db.performanceMetric.findMany({where:{asset:{variant:{jobId}}},orderBy:{createdAt:'desc'},take:200});return NextResponse.json({metrics:rows.map(r=>({...(r.payload as object),id:r.id}))});}
export async function POST(request:Request){const user=await currentUser();if(!user)return error('Sign in required',401);if(!mayCreate(user)&&user.role!=='MEDIA_BUYER')return error('Not permitted',403);const parsed=metricSchema.safeParse(await jsonBody(request));if(!parsed.success)return error('Check source, dates and metric values');const d=parsed.data;const asset=await db.assetVersion.findUnique({where:{id:d.assetId},include:{variant:{include:{job:true}}}});if(!asset)return error('Asset not found',404);if(!await mayView(user,asset.variant.job))return error('Not permitted',403);
 try{const record=await db.$transaction(async tx=>{const prior=await tx.performanceMetric.findUnique({where:{provider_externalId:{provider:d.provider,externalId:d.externalId}}});if(prior){if(prior.assetId!==d.assetId)throw new Error('External result ID already belongs to another asset');return prior;}
 const r=await tx.performanceMetric.create({data:{assetId:d.assetId,provider:d.provider,externalId:d.externalId,payload:d}});await tx.auditEvent.create({data:{jobId:asset.variant.jobId,actorId:user.id,action:'performance.linked',after:{metricId:r.id,assetId:d.assetId,sourceUrl:d.sourceUrl}}});return r;});return NextResponse.json({metric:{...(record.payload as object),id:record.id}})}catch(e){return error((e as Error).message,409)}
}
